@Library('jenkins-shared-library') _
pipeline {
    agent any
    tools {
        maven 'maven3.9'
    }
    environment {
        IMAGE_NAME = 'hello-maven-app'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Build App') {
            steps {
                buildApp(env.IMAGE_NAME, env.IMAGE_TAG)
        
            }
        }

        stage('Build Docker Image') {
            steps {
             buildDockerImage(env.IMAGE_NAME, env.IMAGE_TAG)
            }
        }

        stage('Push to Docker Hub') {
            steps {
                pushToDockerHub(env.IMAGE_NAME, env.IMAGE_TAG)
            }
        }
    }
}


