def pipelineScript

pipeline {
    agent any

    tools {
        maven 'maven3.9'
    }

    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Tag for Docker Image')
        choice(name: 'MAVEN_GOAL', choices: ['clean package -DskipTests', 'clean package', 'clean install'], description: 'Choose Maven goal')
    }

    environment {
        IMAGE_NAME = 'hello-maven-app'
    }

    stages {
        stage('Load Pipeline Script') {
            steps {
                dir('05-hello-maven-scripted-pipeline') { 
                    script {
                        pipelineScript = load 'pipeline.groovy'
                    }
                }
            }
        }
        stage('Build App') {
            steps {
                script {
                    pipelineScript.buildApp(params.MAVEN_GOAL)
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    pipelineScript.buildDockerImage(env.IMAGE_NAME, params.IMAGE_TAG)
                }
            }
        }

        stage('Confirm Push to Docker Hub') {
            steps {
                script {
                    pipelineScript.confirmPushToDockerHub()
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    pipelineScript.pushToDockerHub(env.IMAGE_NAME, params.IMAGE_TAG)
                }
            }
        }
    }
}
