pipeline {
    agent any
    tools {
        maven 'maven3.9'
    }
    environment {
        IMAGE_NAME = 'hello-maven-app'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Build App') {
            steps {
                dir('10-hello-maven-ec2-docker-ssh-deploy-pipeline') {
                echo 'Building the app with Maven'
                sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                 dir('10-hello-maven-ec2-docker-ssh-deploy-pipeline') {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    echo 'Building Docker Image'
                    sh "docker build -t ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG} ."
                }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    echo 'Pushing Docker Image to Docker Hub'
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG}
                        docker logout
                    '''
                }
            }
        }
         stage('Deploy to EC2') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                 script {
                     echo 'Deploying Docker Image to EC2 instance'
                     sshagent(credentials: ['ssh-ec2-eu-west-3-ec2-user']) {
                        sh """
                           echo "Copying script to EC2..."
                           scp 11-hello-maven-ec2-docker-ssh-scriptedDeploy-pipeline/deploy-to-ec2.sh ec2-user@52.47.140.248:/home/ec2-user
                           echo "Running deploy script remotely..."
                           ssh -o StrictHostKeyChecking=no ec2-user@52.47.140.248 '
                           chmod +x deploy-to-ec2.sh && 
                           ./deploy-to-ec2.sh "${DOCKER_PASS}" "${DOCKER_USER}" "${IMAGE_NAME}" "${IMAGE_TAG}"
          '
                    """
                    }
                 }       
               }
            }
         }
      }
   }



